### ISSUE TITLE
Support the same platforms with cert-manager

### ISSUE THREAD

**Issue by anagno** [bwolf/cert-manager-webhook-gandi#17]
Hello and thank you for the nice project,

I would like to use the plugin in a raspberry pi kubernetes cluster, but the official images are only available for amd64. Is it possible to add builds for arm64 ? Probably it makes sense to support the same platforms as [cert-manager](https://quay.io/repository/jetstack/cert-manager-cainjector?tag=v1.6.1&tab=tags). 

I think the necessary changes for supporting the new builds are minimum. The only thing that has to change is the [platforms in the build step](https://github.com/bwolf/cert-manager-webhook-gandi/blob/master/.github/workflows/main.yml#L91)

It should be changed to ```platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x```

Does it make sense to support more platforms?

Kind regards,
Vasileios

**Comment by barsa-net** [comment]
I built it on a RPi4 in arm64 with `docker buildx build --target=image --platform=linux/arm64 --output=type=docker,name=bwolf/cert-manager-webhook-gandi:0.2.0 --tag=cert-manager-webhook-gandi:0.2.0 --build-arg=GO_VERSION=1.17 .` and issued a staging wildcard certificate with letsencrypt, so it looks definitely possible.

Supporting the request as it takes way too long to build on a RPi4 (~600sec)

Kubernetes: `v1.22.7+k3s1`
Cert-manager: `v1.7.1`

**Comment by pygoubet** [comment]
It builds correctly on arm64 architecture.
Just need to remove the hardcoded amd64 achitecture in the [Makefile](https://github.com/bwolf/cert-manager-webhook-gandi/blob/master/Makefile#L41)
```bash
sed 's/amd64/${ARCH}/' Makefile -i
```

**Comment by bwolf** [comment]
Feel free to create a PR for this. Re-open this issue if appropriate.
