### ISSUE TITLE
the server could not find the requested resource

### ISSUE THREAD

**Issue by goldyfruit** [bwolf/cert-manager-webhook-gandi#26]
Hi,

The `cert-manager-webhook-gandi-XXX` pod log is full of these errors:
```
E0303 23:46:52.191455       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PriorityLevelConfiguration: failed to list *v1beta1.PriorityLevelConfiguration: the server could not find the requested resource
E0303 23:46:52.202524       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
E0303 23:46:53.912153       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
E0303 23:46:54.895335       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PriorityLevelConfiguration: failed to list *v1beta1.PriorityLevelConfiguration: the server could not find the requested resource
E0303 23:46:57.618353       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
E0303 23:46:58.412069       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PriorityLevelConfiguration: failed to list *v1beta1.PriorityLevelConfiguration: the server could not find the requested resource
```

I'm running Kubernetes 1.26.1 and Cert-Manager 1.11.0 with version 0.2.0 of this webhook.

**Comment by barsa-net** [comment]
I got the same error and found out that should be loosely related to cert-manager/cert-manager/pull/6085

Updating dependencies seems to fix that, if you are interested about the new dependencies you can refer to [this commit](https://github.com/barsa-net/cert-manager-webhook-gandi/commit/b61c47cea0f13fd66bb9b7e84a1473c227ca157f)

I also built a new set of docker images, if you are willing to give them a try [docker.io/barsanet/cert-manager-webhook-gandi:0.2.0-go1.20](https://hub.docker.com/layers/barsanet/cert-manager-webhook-gandi/0.2.0-go1.20/images/sha256-42875788329d0e891864971cbc64fea821edd189d42622acee33b0ac76e5a029?context=repo)

**Comment by ddevler** [comment]
@barsa-net ty. I tested it with k3s and working. Saved me the time of updating the dependancies and code myself.

**Comment by goldyfruit** [comment]
All good, thanks @barsa-net

**Comment by goldyfruit** [comment]
> I got the same error and found out that should be loosely related to [cert-manager/cert-manager/pull/6085](https://github.com/cert-manager/cert-manager/pull/6085)
> 
> Updating dependencies seems to fix that, if you are interested about the new dependencies you can refer to [this commit](https://github.com/barsa-net/cert-manager-webhook-gandi/commit/b61c47cea0f13fd66bb9b7e84a1473c227ca157f)
> 
> I also built a new set of docker images, if you are willing to give them a try [docker.io/barsanet/cert-manager-webhook-gandi:0.2.0-go1.20](https://hub.docker.com/layers/barsanet/cert-manager-webhook-gandi/0.2.0-go1.20/images/sha256-42875788329d0e891864971cbc64fea821edd189d42622acee33b0ac76e5a029?context=repo)

Do you mind sending a PR to this repo? Maybe @bwolf  would be able to merge it.

EDIT:

You did it already. :+1:
