### ISSUE TITLE
Missing debug logging to further troubleshoot an issue.

### ISSUE THREAD

**Issue by srgvg** [bwolf/cert-manager-webhook-gandi#3]
Hi. First of all, thank you for providing this!

I recently set up certmanager on a cluster, and configured it to be able to issue certificates for all my gandi domains.
For my default nginx setup. I'm requesting a certificate which has all my apex domains and it's respective wildcard.
All the orders work, except for 1 particular wildcard. 

I tried figuring out what the exact error is, but the most specific I can find in the logs is

```
status":{"metadata":{},"status":"Failed","message":"unable to create TXT record: failed creating TXT record: \u003cnil\u003e"}}}
```

from the logged request, I could figure out (I think?) which record needed to be created, and tried to set it up myself (gandi.cli tool), which yielded me zero error.

I'm not sure if there are any other options to try to understand the exact error Gandi returns?

Not sure if that is related here, but I do know, from experience with the gandi.cli tool, their API is a bit a mess, as "https://dns.api.gandi.net/api/v5" is actually an older version, whilst the newer (and different) one is at https://api.gandi.net/api/v5
(I patched gandi.cli to be able to make dns.list work... https://github.com/srgvg/gandi.cli/commit/15004e3e724e5e79c0fbcc495e5bc2057ad9ff92)

**Comment by bwolf** [comment]
Still relevant? If yes: please reopen the issue.
